# Path to Yarn constraints (used for custom rules and dependency policies)
constraintsPath: ./yarn.config.cjs

# Use Plug'n'Play instead of node_modules
nodeLinker: pnp

# Store the Yarn cache locally in the project (useful for Docker and CI)
enableGlobalCache: false

# Disable compression for cached packages (faster installs, especially in Docker)
compressionLevel: 0

# Add missing dependencies to specific packages (temporary fix for broken packages)
packageExtensions:
  "@nestjs-modules/mailer@*":
    dependencies:
      lodash: "*"   # Required but missing in their package.json
      tslib: "*"    # Required but missing in their package.json
