name: API Gateway Test & Deploy (Staging)

on:
  push:
    branches:
      - staging
    paths:
      - 'api-gateway/**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test:e2e
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
          DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EXP_ACC_TIME: ${{ secrets.EXP_ACC_TIME }}
          EXP_REF_TIME: ${{ secrets.EXP_REF_TIME }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          NODEMAILER_APP_PASSWORD: ${{ secrets.NODEMAILER_APP_PASSWORD }}
          NODEMAILER_EMAIL: ${{ secrets.NODEMAILER_EMAIL }}
          PROD_NEST_DATABASE: ${{ secrets.PROD_NEST_DATABASE }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
          THROTTLE_LIMIT: ${{ secrets.THROTTLE_LIMIT }}
          THROTTLE_TTL: ${{ secrets.THROTTLE_TTL }}

  sync-main-branch:
    name: Sync main -> staging
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge staging -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
