name: Enforce Dependency Constraints

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:
    branches: [main, dev, feature/**]

jobs:
  constraints-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20 (match .nvmrc and package.json)
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'  # the exact version as in engines/.nvmrc
          cache: 'yarn'

      - name: Enable Corepack for Yarn Berry
        run: corepack enable

      - name: Use correct Yarn version (4.9.2)
        run: corepack prepare yarn@4.9.2 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies (immutable)
        run: yarn install --immutable

      - name: Run dependency constraints check
        run: yarn constraints
