# .github/workflows/constraints.yml
name: Enforce Dependency Constraints

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:
    branches: [main, dev, feature/**]

jobs:
  constraints-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate Yarn 4.9.2 (matches packageManager)
        run: corepack prepare yarn@4.9.2 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run dependency constraints check
        run: yarn constraints

