# frontend-ci.yml
name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: development
      run_build: false

