# frontend-ci.yml
name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  ci:
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: production
      run_lint: true
      run_tests: true
      run_build: false
    secrets:
      VITE_ANALYTICS_ID: ${{ secrets.VITE_ANALYTICS_ID }}
      VITE_DEV_EMAIL: ${{ secrets.VITE_DEV_EMAIL }}
      VITE_DEV_PASSWORD: ${{ secrets.VITE_DEV_PASSWORD }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}