# .github/workflows/frontend-deploy.yml
name: Frontend Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: production
      run_lint: false
      run_tests: false
      run_build: true
    secrets:
      VITE_ANALYTICS_ID: ${{ secrets.VITE_ANALYTICS_ID }}
      VITE_DEV_EMAIL: ${{ secrets.VITE_DEV_EMAIL }}
      VITE_DEV_PASSWORD: ${{ secrets.VITE_DEV_PASSWORD }}

  upload-artifacts:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'nektos/act' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
