name: Frontend Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vite Frontend

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack & Install dependencies (immutable)
        run: |
          corepack enable
          yarn install --immutable

      - name: Run tests (optional)
        run: yarn test --passWithNoTests

      - name: Build frontend
        run: yarn build --mode production

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist
