name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack & Check Yarn
        run: corepack enable && yarn --version

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn check:types

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build
