# .github/workflows/frontend-deploy.yml
name: Frontend Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: production
      run_lint: false
      run_tests: false

    outputs:
      artifact_name: frontend-dist

    steps:
      - name: Upload build artifacts
        if: ${{ inputs.run_build && env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  upload-artifacts:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'nektos/act' }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist

      - name: (optional) Do something with the artifact
        run: ls -la frontend/dist
